export const customStyle = {
  stepIndicatorSize: 25,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: '#2aa964',
  stepStrokeFinishedColor: '#2aa964',
  stepStrokeUnFinishedColor: '#dedede',
  separatorFinishedColor: '#2aa964',
  separatorUnFinishedColor: '#dedede',
  stepIndicatorFinishedColor: '#2aa964',
  stepIndicatorUnFinishedColor: '#d4ede0',
  stepIndicatorCurrentColor: '#2aa964',
  stepIndicatorLabelFontSize: 12,
  currentStepIndicatorLabelFontSize: 0,
  stepIndicatorLabelCurrentColor: 'transparent',
  stepIndicatorLabelFinishedColor: 'transparent',
  stepIndicatorLabelUnFinishedColor: 'transparent',
  labelColor: '#848484',
  labelSize: 12,
  currentStepLabelColor: '#6E6E6E',
};
